title: Stack Problems
description: A Passionate Programmer and Hiker
author: Jinpeng LV
github: https://github.com/gepolv
about: A Passionate Programmer and Hiker.

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/jinpeng-lv-94a40018"
    - icon: fa-stack-exchange
      link: "http://stackoverflow.com/users/665023/derek"

# share:
#   twitter_username: agusmakmun6
#   fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Github
      url: https://github.com/gepolv
    - text: XML Feed
      url: /feed.xml

url: "https://gepolv.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist
